### ISSUE TITLE
[Issue] domain add fails due to incorrect domain formatting 

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#46] opened 2021-03-29 02:29 UTC
I was running ``cat domains.txt |bbrf domain add - -s subfinder  --show-new`` and got this error:

``[ERROR] string indices must be integers ``

I found some domains (from subfinder) starting with '_', character that is not allowed. 

It would be cool/nice to have a warning/error message when these type of formatting errors are found.

**Comment by honoki** [comment] 2021-03-29 06:13
Hi @pdelteil - the underscore is unlikely to be the issue here, as they should be allowed since v1.1.2 or otherwise ignored; I am planning to add more verbosity to error messages in debug mode to help troubleshoot this. It looks like the error is a result of an unexpected response from the BBRF server, rather than malformed input. I'm going to assume this is the same root cause as #44 unless this persists after that is resolved.

Closing for now!

**Closed by honoki** 2021-03-29 06:13 UTC

**Comment by honoki** [comment] 2021-03-29 09:04
> I found some domains (from subfinder) starting with '_', character that is not allowed.

Turns out this was exactly the problem 😅
